#!/usr/bin/env python

import os
import time
import subprocess
import musicbrainzngs
from pypresence import Presence

class RPC:
	def __init__(self, client_id):
		self.rpc = Presence(client_id)
		self.elapsed_time = 0
		self.playing = False
		musicbrainzngs.set_useragent("cmrpc", "0.1", "https://gitlab.com/saibakho/cmrpc")

	def start(self):
		while True:
			try:
				subprocess.check_output(["pgrep", "cmus"])
				break
			except:
				print("[ERROR] No cmus server found. Exit.")
				time.sleep(1)
		try:
			cur_song = ""
			self.rpc.connect()
			print("[OK] RPC started.")

			while True:
				time.sleep(1)
				status = self.get_status()
				if not self.playing:
					self.rpc.clear()
					cur_song = ""
					continue
				if cur_song != status["title"]:
					cur_song = status["title"]
					# extract cover from mp3

					cover_dir = os.path.expanduser("~/.config/cmus/covers")
					cover_path = "%s/%s.jpg"%(cover_dir, hash(status["album"].replace(" ", "")))
					filename = status["file"].replace("'", "'\\''")
 
					if not os.path.exists(cover_path):
						if len(os.listdir(cover_dir)) > 10:
							os.system("rm -rf %s"%cover_dir)
						os.system("mkdir -p %s"%cover_dir)
						#subprocess.run[("ffmpeg", "-i", "'%s'"%status["file"], "-an", "-vcodec", "copy", "temp.jpg")]
						os.system("ffmpeg -i '%s' -an -vcodec copy %s 2>/dev/null"%(filename, cover_path))
					self.notify(status, cover_path)

					# fetch cover url from MusicBrainz
					try:
						result = musicbrainzngs.search_releases(query=status["album"], artist=status["albumartist"])
						cover_url = "https://coverartarchive.org/release-group/%s/front"%result["release-list"][0]["release-group"]["id"]
					except:
						print("[ERROR] Fetch cover from MusicBrainz failed.")
						cover_url = "captivate"
					
					print(status)
					self.rpc.update(
						large_image=cover_url,
						small_image="play-black",# if status["status"] == "playing" else "pause-black",
						large_text=status["album"],
						small_text=status["length"],
						details="%s"%status["title"],
						state="%s"%status["artist"],
						start=time.time()-self.elapsed_time
					)
		except:
			pass
		finally:
			self.rpc.close()
			print("[OK] RPC closed.")
		#	icons source:
		#	https://www.flaticon.com/free-icon/pause_709691
		#	https://www.flaticon.com/free-icon/play-button_109197

	def get_status(self):
		ret = {}
		for line in subprocess.check_output(["cmus-remote", "-C", "status"]).decode("utf-8").split("\n"):
			params = line.split()
			if params == []:
				continue

			match params[0]:
				case "status":
					self.playing = params[1] == "playing"
				case "file":
					ret["file"] = " ".join(params[1:])
				case "duration":
					num = int(params[1])
					ret["length"] = "%s%02d : %02d"%("%02d : "%(
						num/3600) if num > 3600 else "", (num/60)%60, num%60)
				case "position":
					self.elapsed_time = int(params[1])
				case "tag":
					ret[params[1]] = " ".join(params[2:])
		return ret

	def notify(self, status, cover_path):
		if not os.path.exists(cover_path):
			cover_path = "$PWD/assets/captivate.jpg"	# $PWD is not a good practice
		os.system("notify-send -i %s 'Title : %s\nArtist : %s\nAlbum : %s\nLength : %s'"%
			(cover_path, status["title"], status["artist"], status["album"], status["length"]))

	def fetch_cover_url(self, status):
		query = "https://musicbrainz.org/ws/2/release/?query=artist:%s&release:%s&limit=1"%(status["albumartist"], status["album"])
		# parse
		return "https://coverartarchive.org/release-group/%s/front"%group_id

if __name__ == "__main__":
	RPC("989349655831785523").start()
	#result = musicbrainzngs.search_releases(query="μοναξιά", artist="nomico")
	#for item in result["release-list"]:
	#	print(item["artist-credit"][0]["name"])

	# ==> todos:
	# 1. jp2a visualizer
	# 2. button jump to MusicBrain album page

	# ==> fixes
	# 1. better search (filter with artist, track num, released year, etc)
	# 2. replace ffmpeg with musicbrainzngs